import { TFish } from "./src/types";

export const dataAllFish: TFish[] = [
  {
    id: 0,
    name: "Pufferfish",
    location: "Ocean, Ginger Island Ocean",
    time: "12pm-4pm",
    imageUrl:
      "https://stardewvalleywiki.com/mediawiki/images/b/ba/Pufferfish.png",
    sellPrice: [
      [200, 250, 300, 400],
      [250, 312, 375, 500],
      [300, 375, 450, 600],
    ],
    description: "Inflates when threatened",
    season: "Summer, All Seasons Ginger Island",
    difficulty: "80",
    usedIn: [
      "Speacialty Fish Bundle",
      "Abigail loved Gift",
      "Aquatic Research Quest",
    ],
    weather: "Sun",
  },
  {
    id: 1,
    name: "Anchovy",
    location: "Ocean",
    time: "Anytime",
    imageUrl: "https://stardewvalleywiki.com/mediawiki/images/7/79/Anchovy.png",
    sellPrice: [
      [30, 37, 45, 60],
      [37, 46, 56, 75],
      [45, 55, 67, 90],
    ],
    description: "A small silver fish found in the ocean",
    season: "Spring and Fall",
    difficulty: "30",
    usedIn: [],
    weather: "Any",
  },
  {
    id: 2,
    imageUrl: "https://stardewvalleywiki.com/mediawiki/images/c/c5/Tuna.png",
    name: "Tuna",
    description: "A large fish that lives in the ocean.",
    sellPrice: [
      [100, 125, 150, 200],
      [125, 156, 187, 250],
      [150, 187, 225, 300],
    ],
    location: "Ocean, Ginger Island Ocean",
    time: "6am-7pm",
    season: "Summer, Winter, All Seasons Ginger Island",
    weather: "Any",
    difficulty: "70",
    usedIn: ["Ocean Fish Bundle", "Quality Fish Bundle", "Fish Taco"],
  },
  {
    id: 3,
    imageUrl: "https://stardewvalleywiki.com/mediawiki/images/0/04/Sardine.png",
    name: "Sardine",
    description: "A common ocean fish.",
    sellPrice: [
      [40, 50, 60, 80],
      [50, 62, 75, 100],
      [60, 75, 90, 120],
    ],
    location: "Ocean",
    time: "6am-7pm",
    season: "Spring, Fall, and Winter",
    weather: "Any",
    difficulty: "30",
    usedIn: ["Ocean Fish Bundle", "Dish O' The Sea"],
  },
  {
    id: 4,
    imageUrl: "",
    name: "Bream",
    description: "",
    sellPrice: [[], [], []],
    location: "",
    time: "",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 5,
    imageUrl: "",
    name: "Largemouth Bass",
    description: "",
    sellPrice: [[], [], []],
    location: "",
    time: "",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 6,
    imageUrl: "",
    name: "Smallmouth Bass",
    description: "",
    sellPrice: [[], [], []],
    location: "",
    time: "",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 7,
    imageUrl: "",
    name: "Rainbow Trout",
    description: "",
    sellPrice: [[], [], []],
    location: "",
    time: "",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 8,
    imageUrl: "",
    name: "Salmon",
    description: "",
    sellPrice: [[], [], []],
    location: "",
    time: "",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 9,
    imageUrl: "",
    name: "Walleye",
    description: "",
    sellPrice: [[], [], []],
    location: "",
    time: "",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 10,
    imageUrl: "",
    name: "Perch",
    description: "",
    sellPrice: [[], [], []],
    location: "",
    time: "",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 11,
    imageUrl: "",
    name: "Carp",
    description: "",
    sellPrice: [[], [], []],
    location: "",
    time: "",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 12,
    imageUrl: "",
    name: "Catfish",
    description: "",
    sellPrice: [[], [], []],
    location: "",
    time: "",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 13,
    imageUrl: "",
    name: "Pike",
    description: "",
    sellPrice: [[], [], []],
    location: "",
    time: "",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 14,
    imageUrl: "",
    name: "Sunfish",
    description: "",
    sellPrice: [[], [], []],
    location: "",
    time: "",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 15,
    imageUrl: "",
    name: "Red Mullet",
    description: "",
    sellPrice: [[], [], []],
    location: "",
    time: "",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 16,
    imageUrl: "",
    name: "Herring",
    description: "",
    sellPrice: [[], [], []],
    location: "",
    time: "",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 17,
    imageUrl: "",
    name: "Eel",
    description: "",
    sellPrice: [[], [], []],
    location: "",
    time: "",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 18,
    imageUrl: "",
    name: "Octopus",
    description: "",
    sellPrice: [[], [], []],
    location: "",
    time: "",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 19,
    imageUrl: "",
    name: "Red Snapper",
    description: "",
    sellPrice: [[], [], []],
    location: "",
    time: "",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 20,
    imageUrl: "",
    name: "Squid",
    description: "",
    sellPrice: [[], [], []],
    location: "",
    time: "",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 21,
    imageUrl: "",
    name: "Sea Cucumber",
    description: "",
    sellPrice: [[], [], []],
    location: "",
    time: "",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 22,
    imageUrl: "",
    name: "Super Cucumber",
    description: "",
    sellPrice: [[], [], []],
    location: "",
    time: "",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 23,
    imageUrl: "",
    name: "Ghostfish",
    description: "",
    sellPrice: [[], [], []],
    location: "",
    time: "",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 24,
    imageUrl: "",
    name: "Stonefish",
    description: "",
    sellPrice: [[], [], []],
    location: "",
    time: "",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 25,
    imageUrl: "",
    name: "Ice Pip",
    description: "",
    sellPrice: [[], [], []],
    location: "",
    time: "",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 26,
    imageUrl: "",
    name: "Lava Eel",
    description: "",
    sellPrice: [[], [], []],
    location: "",
    time: "",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 27,
    imageUrl: "",
    name: "Sandfish",
    description: "",
    sellPrice: [[], [], []],
    location: "",
    time: "",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 28,
    imageUrl: "",
    name: "Scorpion Carp",
    description: "",
    sellPrice: [[], [], []],
    location: "",
    time: "",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 29,
    imageUrl: "",
    name: "Flounder",
    description: "",
    sellPrice: [[], [], []],
    location: "",
    time: "",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 30,
    imageUrl: "",
    name: "Midnight Carp",
    description: "",
    sellPrice: [[], [], []],
    location: "",
    time: "",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 31,
    imageUrl: "",
    name: "Sturgeon",
    description: "",
    sellPrice: [[], [], []],
    location: "",
    time: "",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 32,
    imageUrl: "",
    name: "Tiger Trout",
    description: "",
    sellPrice: [[], [], []],
    location: "",
    time: "",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 33,
    imageUrl: "",
    name: "Bullhead",
    description: "",
    sellPrice: [[], [], []],
    location: "",
    time: "",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 34,
    imageUrl: "",
    name: "Tilapia",
    description: "",
    sellPrice: [[], [], []],
    location: "",
    time: "",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 35,
    imageUrl: "",
    name: "Chub",
    description: "",
    sellPrice: [[], [], []],
    location: "",
    time: "",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 36,
    imageUrl: "",
    name: "Dorado",
    description: "",
    sellPrice: [[], [], []],
    location: "",
    time: "",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 37,
    imageUrl: "",
    name: "Albacore",
    description: "",
    sellPrice: [[], [], []],
    location: "",
    time: "",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 38,
    imageUrl: "",
    name: "Shad",
    description: "",
    sellPrice: [[], [], []],
    location: "",
    time: "",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 39,
    imageUrl: "",
    name: "Lingcod",
    description: "",
    sellPrice: [[], [], []],
    location: "",
    time: "",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 40,
    imageUrl: "",
    name: "Halibut",
    description: "",
    sellPrice: [[], [], []],
    location: "",
    time: "",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 41,
    imageUrl: "",
    name: "Void Salmon",
    description: "",
    sellPrice: [[], [], []],
    location: "",
    time: "",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 42,
    imageUrl: "",
    name: "Slimejack",
    description: "",
    sellPrice: [[], [], []],
    location: "",
    time: "",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 43,
    imageUrl: "",
    name: "Stingray",
    description: "",
    sellPrice: [[], [], []],
    location: "",
    time: "",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 44,
    imageUrl: "",
    name: "Lionfish",
    description: "",
    sellPrice: [[], [], []],
    location: "",
    time: "",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 45,
    imageUrl: "",
    name: "Blue Discus",
    description: "",
    sellPrice: [[], [], []],
    location: "",
    time: "",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 46,
    imageUrl: "",
    name: "Goby",
    description: "",
    sellPrice: [[], [], []],
    location: "",
    time: "",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
];

// Outline:
// {
//     id: 0,
//     imageUrl: "",
//     name: "",
//     description: "",
//     sellPrice: [[],[],[]],
//     location: "",
//     time: "",
//     season: "",
//     weather: "",
//     difficulty: "",
//     usedIn: [],
//   }
