import { TFish } from "./src/types";

export const dataAllFish: TFish[] = [
  {
    id: 0,
    name: "Pufferfish",
    location: "Ocean, Ginger Island Ocean",
    time: "12pm - 4pm",
    imageUrl:
      "https://stardewvalleywiki.com/mediawiki/images/b/ba/Pufferfish.png",
    sellPrice: [
      [200, 250, 300, 400],
      [250, 312, 375, 500],
      [300, 375, 450, 600],
    ],
    description: "Inflates when threatened",
    season: "Summer, All Seasons Ginger Island",
    difficulty: "80",
    usedIn: [
      "Speacialty Fish Bundle",
      "Abigail loved Gift",
      "Aquatic Research Quest",
    ],
    weather: "Sun",
  },
  {
    id: 1,
    name: "Anchovy",
    location: "Ocean",
    time: "Anytime",
    imageUrl: "https://stardewvalleywiki.com/mediawiki/images/7/79/Anchovy.png",
    sellPrice: [
      [30, 37, 45, 60],
      [37, 46, 56, 75],
      [45, 55, 67, 90],
    ],
    description: "A small silver fish found in the ocean",
    season: "Spring and Fall",
    difficulty: "30",
    usedIn: [],
    weather: "Any",
  },
  {
    id: 2,
    imageUrl: "https://stardewvalleywiki.com/mediawiki/images/c/c5/Tuna.png",
    name: "Tuna",
    description: "A large fish that lives in the ocean.",
    sellPrice: [
      [100, 125, 150, 200],
      [125, 156, 187, 250],
      [150, 187, 225, 300],
    ],
    location: "Ocean, Ginger Island Ocean",
    time: "6am - 7pm",
    season: "Summer, Winter, All Seasons Ginger Island",
    weather: "Any",
    difficulty: "70",
    usedIn: ["Ocean Fish Bundle", "Quality Fish Bundle", "Fish Taco"],
  },
  {
    id: 3,
    imageUrl: "https://stardewvalleywiki.com/mediawiki/images/0/04/Sardine.png",
    name: "Sardine",
    description: "A common ocean fish.",
    sellPrice: [
      [40, 50, 60, 80],
      [50, 62, 75, 100],
      [60, 75, 90, 120],
    ],
    location: "Ocean",
    time: "6am - 7pm",
    season: "Spring, Fall, and Winter",
    weather: "Any",
    difficulty: "30",
    usedIn: ["Ocean Fish Bundle", "Dish O' The Sea"],
  },
  {
    id: 4,
    imageUrl: "https://stardewvalleywiki.com/mediawiki/images/8/82/Bream.png",
    name: "Bream",
    description: "A fairly common river fish that becomes active at night.",
    sellPrice: [[], [], []],
    location: "River (Town & Forest)",
    time: "6pm – 2am",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 5,
    imageUrl:
      "https://stardewvalleywiki.com/mediawiki/images/1/11/Largemouth_Bass.png",
    name: "Largemouth Bass",
    description: "A popular fish that lives in lakes.",
    sellPrice: [[], [], []],
    location: "The Mountain Lake",
    time: "6am – 7pm",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 6,
    imageUrl:
      "https://stardewvalleywiki.com/mediawiki/images/a/a5/Smallmouth_Bass.png",
    name: "Smallmouth Bass",
    description: "A freshwater fish that is very sensitive to pollution.",
    sellPrice: [[], [], []],
    location: "River (Town) and Forest Pond",
    time: "Anytime",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 7,
    imageUrl:
      "https://stardewvalleywiki.com/mediawiki/images/1/14/Rainbow_Trout.png",
    name: "Rainbow Trout",
    description: "A freshwater trout with colorful markings.",
    sellPrice: [[], [], []],
    location: "River (Town & Forest), Forest Pond, and The Mountain Lake",
    time: "6am – 7pm",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 8,
    imageUrl: "https://stardewvalleywiki.com/mediawiki/images/e/e0/Salmon.png",
    name: "Salmon",
    description: "Swims upstream to lay its eggs.",
    sellPrice: [[], [], []],
    location: "River (Town & Forest), Forest Pond, and The Mountain Lake",
    time: "6am – 7pm",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 9,
    imageUrl: "https://stardewvalleywiki.com/mediawiki/images/0/05/Walleye.png",
    name: "Walleye",
    description: "A freshwater fish caught at night.",
    sellPrice: [[], [], []],
    location: "The Mountain, Lake, Secret Woods Pond, and The Sewers",
    time: "12pm – 2am",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 10,
    imageUrl: "https://stardewvalleywiki.com/mediawiki/images/4/43/Perch.png",
    name: "Perch",
    description: "A freshwater fish of the winter.",
    sellPrice: [[], [], []],
    location: "River (Town & Forest), Secret Woods Pond, and Witch's Swamp",
    time: "Anytime",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 11,
    imageUrl: "https://stardewvalleywiki.com/mediawiki/images/a/a8/Carp.png",
    name: "Carp",
    description: "A common pond fish.",
    sellPrice: [[], [], []],
    location: "River (Town & Forest) and Forest Pond",
    time: "Anytime",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 12,
    imageUrl: "https://stardewvalleywiki.com/mediawiki/images/9/99/Catfish.png",
    name: "Catfish",
    description: "An uncommon fish found in streams.",
    sellPrice: [[], [], []],
    location: "River (Town & Forest)",
    time: "6am – 12am",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 13,
    imageUrl: "https://stardewvalleywiki.com/mediawiki/images/3/31/Pike.png",
    name: "Pike",
    description: "A freshwater fish that's difficult to catch.",
    sellPrice: [[], [], []],
    location: "Ocean",
    time: "Anytime",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 14,
    imageUrl: "https://stardewvalleywiki.com/mediawiki/images/5/56/Sunfish.png",
    name: "Sunfish",
    description: "A common river fish.",
    sellPrice: [[], [], []],
    location: "Ocean",
    time: "6am – 7pm",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 15,
    imageUrl:
      "https://stardewvalleywiki.com/mediawiki/images/f/f2/Red_Mullet.png",
    name: "Red Mullet",
    description: "Long ago these were kept as pets.",
    sellPrice: [[], [], []],
    location: "Ocean",
    time: "6am – 7pm",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 16,
    imageUrl: "https://stardewvalleywiki.com/mediawiki/images/f/f1/Herring.png",
    name: "Herring",
    description: "A common ocean fish.",
    sellPrice: [[], [], []],
    location: "Ocean",
    time: "Anytime",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 17,
    imageUrl: "https://stardewvalleywiki.com/mediawiki/images/9/91/Eel.png",
    name: "Eel",
    description: "A long, slippery little fish.",
    sellPrice: [[], [], []],
    location: "Ocean",
    time: "4pm – 2am",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 18,
    imageUrl: "https://stardewvalleywiki.com/mediawiki/images/5/5a/Octopus.png",
    name: "Octopus",
    description: "A mysterious and intelligent creature.",
    sellPrice: [[], [], []],
    location: "Ocean",
    time: "6am – 1pm",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 19,
    imageUrl:
      "https://stardewvalleywiki.com/mediawiki/images/d/d3/Red_Snapper.png",
    name: "Red Snapper",
    description: "A popular fish with a nice red color.",
    sellPrice: [[], [], []],
    location: "Ocean",
    time: "6am – 7pm",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 20,
    imageUrl: "https://stardewvalleywiki.com/mediawiki/images/8/81/Squid.png",
    name: "Squid",
    description: "A deep sea creature that can grow to enormous size.",
    sellPrice: [[], [], []],
    location: "Ocean",
    time: "6pm – 2am",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 21,
    imageUrl:
      "https://stardewvalleywiki.com/mediawiki/images/a/a9/Sea_Cucumber.png",
    name: "Sea Cucumber",
    description: "A slippery, slimy creature found on the ocean floor.",
    sellPrice: [[], [], []],
    location: "Ocean",
    time: "6am – 7pm",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 22,
    imageUrl:
      "https://stardewvalleywiki.com/mediawiki/images/d/d5/Super_Cucumber.png",
    name: "Super Cucumber",
    description: "A rare, purple variety of sea cucumber.",
    sellPrice: [[], [], []],
    location: "Ocean and Ginger Island Oceans",
    time: "6pm – 2am",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 23,
    imageUrl:
      "https://stardewvalleywiki.com/mediawiki/images/7/72/Ghostfish.png",
    name: "Ghostfish",
    description: "A pale, blind fish found in underground lakes.",
    sellPrice: [[], [], []],
    location: "The Mines floors 20 & 60, and Ghost Drops",
    time: "Anytime",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 24,
    imageUrl:
      "https://stardewvalleywiki.com/mediawiki/images/0/03/Stonefish.png",
    name: "Stonefish",
    description: "A bizarre fish that's shaped like a brick.",
    sellPrice: [[], [], []],
    location: "The Mines floor 20",
    time: "Anytime",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 25,
    imageUrl: "https://stardewvalleywiki.com/mediawiki/images/6/63/Ice_Pip.png",
    name: "Ice Pip",
    description: "A rare fish that thrives in extremely cold conditions.",
    sellPrice: [[], [], []],
    location: "The Mines floor 60",
    time: "Anytime",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 26,
    imageUrl:
      "https://stardewvalleywiki.com/mediawiki/images/1/12/Lava_Eel.png",
    name: "Lava Eel",
    description: "It can somehow survive in pools of red-hot lava.",
    sellPrice: [[], [], []],
    location: "The Mines floor 100 and Volcano Caldera",
    time: "Anytime",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 27,
    imageUrl:
      "https://stardewvalleywiki.com/mediawiki/images/b/bb/Sandfish.png",
    name: "Sandfish",
    description: "It tries to hide using camouflage.",
    sellPrice: [[], [], []],
    location: "The Desert",
    time: "6am – 8pm",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 28,
    imageUrl:
      "https://stardewvalleywiki.com/mediawiki/images/7/76/Scorpion_Carp.png",
    name: "Scorpion Carp",
    description: "It's like a regular carp but with a sharp stinger.",
    sellPrice: [[], [], []],
    location: "The Desert (Requires fishing level 4)",
    time: "6am – 8pm",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 29,
    imageUrl:
      "https://stardewvalleywiki.com/mediawiki/images/8/85/Flounder.png",
    name: "Flounder",
    description: "It lives on the bottom, so both eyes are on top of its head.",
    sellPrice: [[], [], []],
    location: "Ocean and Ginger Island Oceans",
    time: "6am – 8pm",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 30,
    imageUrl:
      "https://stardewvalleywiki.com/mediawiki/images/3/33/Midnight_Carp.png",
    name: "Midnight Carp",
    description: "This shy fish only feels comfortable at night.",
    sellPrice: [[], [], []],
    location:
      "The Mountain Lake, Cindersap Forest pond, Ginger Island Pond and Rivers",
    time: "10pm – 2am",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 31,
    imageUrl:
      "https://stardewvalleywiki.com/mediawiki/images/4/42/Sturgeon.png",
    name: "Sturgeon",
    description:
      "An ancient bottom-feeder with a dwindling population. Females can live up to 150 years.",
    sellPrice: [[], [], []],
    location: "The Mountain Lake",
    time: "6am – 7pm",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 32,
    imageUrl:
      "https://stardewvalleywiki.com/mediawiki/images/0/01/Tiger_Trout.png",
    name: "Tiger Trout",
    description: "A rare hybrid trout that cannot bear offspring of its own.",
    sellPrice: [[], [], []],
    location: "River (Town & Forest)",
    time: "6am – 7pm",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 33,
    imageUrl:
      "https://stardewvalleywiki.com/mediawiki/images/d/db/Bullhead.png",
    name: "Bullhead",
    description:
      "A relative of the catfish that eats a variety of foods off the lake bottom.",
    sellPrice: [[], [], []],
    location: "The Mountain Lake",
    time: "Anytime",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 34,
    imageUrl: "https://stardewvalleywiki.com/mediawiki/images/7/73/Tilapia.png",
    name: "Tilapia",
    description: "A primarily vegetarian fish that prefers warm water.",
    sellPrice: [[], [], []],
    location: "Ocean and Ginger Island Oceans",
    time: "6am – 2pm",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 35,
    imageUrl: "https://stardewvalleywiki.com/mediawiki/images/b/bd/Chub.png",
    name: "Chub",
    description: "A common freshwater fish known for its voracious appetite.",
    sellPrice: [[], [], []],
    location: "Cindersap Forest River and The Mountain Lake",
    time: "Anytime",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 36,
    imageUrl: "https://stardewvalleywiki.com/mediawiki/images/1/18/Dorado.png",
    name: "Dorado",
    description: "A fierce carnivore with brilliant orange scales.",
    sellPrice: [[], [], []],
    location: "Cindersap Forest River",
    time: "6am – 7pm",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 37,
    imageUrl:
      "https://stardewvalleywiki.com/mediawiki/images/e/e1/Albacore.png",
    name: "Albacore",
    description: "Prefers temperature 'edges' where cool and warm water meet.",
    sellPrice: [[], [], []],
    location: "Ocean",
    time: "6am – 11am and 6pm – 2am",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 38,
    imageUrl: "https://stardewvalleywiki.com/mediawiki/images/e/ef/Shad.png",
    name: "Shad",
    description:
      "Lives in a school at sea, but returns to the rivers to spawn.",
    sellPrice: [[], [], []],
    location: "River (Town & Forest)",
    time: "9am – 2am",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 39,
    imageUrl: "https://stardewvalleywiki.com/mediawiki/images/8/87/Lingcod.png",
    name: "Lingcod",
    description:
      "A fearsome predator that will eat almost anything it can cram into its mouth.",
    sellPrice: [[], [], []],
    location: "River (Town & Forest) and The Mountain Lake",
    time: "Anytime",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 40,
    imageUrl: "https://stardewvalleywiki.com/mediawiki/images/0/02/Halibut.png",
    name: "Halibut",
    description: "A flat fish that lives on the ocean floor.",
    sellPrice: [[], [], []],
    location: "Ocean",
    time: "6am – 11am and 7pm – 2am",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 41,
    imageUrl:
      "https://stardewvalleywiki.com/mediawiki/images/a/ad/Void_Salmon.png",
    name: "Void Salmon",
    description:
      "A salmon, twisted by void energy. The fresh meat is jet black, but rapidly turns pink when exposed to air.",
    sellPrice: [[], [], []],
    location: "Witch's Swamp",
    time: "Anytime",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 42,
    imageUrl:
      "https://stardewvalleywiki.com/mediawiki/images/3/34/Slimejack.png",
    name: "Slimejack",
    description:
      "He's coated in a very thick layer of slime. He keeps slipping out of your hands!",
    sellPrice: [[], [], []],
    location: "Mutant Bug Lair",
    time: "Anytime",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 43,
    imageUrl:
      "https://stardewvalleywiki.com/mediawiki/images/3/3a/Stingray.png",
    name: "Stingray",
    description:
      "Despite having a toxic stinger, these fish are shy and prefer to avoid humans.",
    sellPrice: [[], [], []],
    location: "Pirate Cove (Ginger Island)",
    time: "Anytime",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 44,
    imageUrl:
      "https://stardewvalleywiki.com/mediawiki/images/b/bb/Lionfish.png",
    name: "Lionfish",
    description: "An aggressive, predatory fish with venomous spines.",
    sellPrice: [[], [], []],
    location: "Ginger Island Ocean",
    time: "Anytime",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 45,
    imageUrl:
      "https://stardewvalleywiki.com/mediawiki/images/e/ee/Blue_Discus.png",
    name: "Blue Discus",
    description:
      "A brightly colored tropical fish that is popular in aquariums.",
    sellPrice: [[], [], []],
    location: "Ginger Island Pond and Rivers",
    time: "Anytime",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 46,
    imageUrl: "https://stardewvalleywiki.com/mediawiki/images/6/67/Goby.png",
    name: "Goby",
    description: "Some types of Gobies can climb up waterfalls.",
    sellPrice: [[], [], []],
    location: "Cindersap Forest Waterfalls",
    time: "Anytime",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
  {
    id: 47,
    imageUrl:
      "https://stardewvalleywiki.com/mediawiki/images/9/97/Woodskip.png",
    name: "Woodskip",
    description:
      "A very sensitive fish that can only live in pools deep in the forest.",
    sellPrice: [[], [], []],
    location: "Secret Woods Pond and Forest Farm",
    time: "Anytime",
    season: "",
    weather: "",
    difficulty: "",
    usedIn: [],
  },
];

// Outline:
// {
//     id: 0,
//     imageUrl: "",
//     name: "",
//     description: "",
//     sellPrice: [[],[],[]],
//     location: "",
//     time: "",
//     season: "",
//     weather: "",
//     difficulty: "",
//     usedIn: [],
//   }
